@startuml
'https://plantuml.com/class-diagram

TestWorttrainerModel ..> WortListe : <use>
TestWorttrainerModel ..> WortTrainer : <use>
TestWorttrainerPersistence ..> SpeichernUndLaden : <use>
WortTrainer "1" o-> "1" WortListe : - wortListe
SpeichernUndLaden "*" --> "1" WortTrainer
SpeichernUndLaden ..|> SpeichernUndLadenStrategie : <implements>
WortFrame --|> JFrame
WortPanel --|> JPanel

package Model {
class WortListe {
- wortListe: Map<String, String>
- {static} URL_PATTERN: Pattern
+ WortListe()
+ WortListe(wort : String, url : String)
+ addWortEintrag(wort : String, url : String) : void
+ delWortEintrag(wort : String) : boolean
+ getWortEintrag(wort : String) : String[2]
+ getWortListe(wort: String) : Map<String, String>
+ setWortListe(wortListe : Map<String, String>) : void
+ showWortListe(): String
+ length(): int
+ {static} checkWort(wort: String): boolean
+ {static} checkUrl(url: String): boolean
}

class WortTrainer {
- wortListe : WortListe[1]
- aktuell : String[2]
- abgefragt : int
- korrekt : int
- / statistic : StringBuilder
+ WortTrainer(wortListe : WortListe)
+ ausgewaehlt() : String[]
+ randomWortEintrag() : String[]
+ check(wort : String) : boolean
+ checkIgnoreCase(wort : String) : boolean
+ getStatistic() : String
+ getAbgefragt() : int
+ setAbgefragt(abgefragt : int) : void
+ getKorrekt() : int
+ setKorrekt(korrekt : int) : void
+ getAktuell() : String[]
+ setAktuell(eintrag : String[]) : void
+ getWortListe() : WortListe
+ reset(): void
}

interface SpeichernUndLadenStrategie {
+ speichern(wortTrainer : WortTrainer) : void
+ laden() : WortTrainer
}

class SpeichernUndLaden {
- speicherpfad : String[1]
+ SpeichernUndLaden()
+ speichern(wortTrainer : WortTrainer) : void
+ laden() : WortTrainer
+ getSpeicherPfad() : String
+ setSpeicherPfad(speicherpfad : String) : void
}


class TestWorttrainerModel {
- wortListe: WortListe
- wortListe2: WortListe
- wortListe3: WortListe
+ setup() : void
+ notNullEmptyInvalid() : void
+ showTest() : void
+ addingMatchingTest() : void
+ getterTest(): void
+ setterTest() : void
+ lengthTest() : void
+ deleteTest() : void
+ getEintragTest() : void
+ alreadyInListTest() : void
+ wortCheckerTest() : void
+ urlCheckerTest() : void
}
}

package View {
class WortFrame {
+ WortFrame(layoutPanel : WortPanel)
- menubar() : JMenuBar
+ {static} main(args : Strins[]) : void
}
class WortPanel {
- wortController: WortController
- bAdd: JButton
- bReset: JButton
- textField: JTextField
- image: JLabel
- question: JLabel
- correct: JLabel
- amount: JLabel
- correctCounter: JLabel
- amountCounter: JLabel
+ WortPanel(wortController: WortController, picture: ImageIcon, correct: int, amount: int)
+ setImage(picture: ImageIcon): void
+ getTextfield(): String
+ refresh(isCorrect: boolean, correctCounter: int, amountCounter: int, picture: ImageIcon): void
+ reset(): void
}
}
@enduml