@startuml
'https://plantuml.com/class-diagram

interface SpeichernUndLadenStrategie
TestWorttrainerModel ..> WortListe : <use>
TestWorttrainerModel ..> WortTrainer : <use>
TestWorttrainerPersistence ..> SpeichernUndLaden : <use>
WortTrainer "1" o-> "1" WortListe : - wortListe
SpeichernUndLaden "*" --> "1" WortTrainer
SpeichernUndLaden ..|> SpeichernUndLadenStrategie : <implements>
WortFrame --|> JFrame: <extends>
WortPanel --|> JPanel: <extends>
WortController "*" --> "1" WortFrame : - wortView
note "- wortView und - wortController" as N1
WortController "*" <--> "*" WortPanel
WortController .. N1
N1 .. WortPanel
WortController "*" --> "1" WortTrainer : -wortTrainer
WortController "*" --> "1" SpeichernUndLaden
interface ActionListener
interface DocumentListener
interface KeyListener
interface WindowListener
WortController ..|> ActionListener : <<implements>>
WortController ..|> DocumentListener : <<implements>>
WortController ..|> KeyListener : <<implements>>
WortController ..|> WindowListener : <<implements>>


package Model {
class WortListe {
- wortListe: Map<String, String>
- {static} URL_PATTERN: Pattern
+ WortListe()
+ WortListe(wort : String, url : String)
+ addWortEintrag(wort : String, url : String) : void
+ delWortEintrag(wort : String) : boolean
+ getWortEintrag(wort : String) : String[2]
+ getWortListe(wort: String) : Map<String, String>
+ setWortListe(wortListe : Map<String, String>) : void
+ showWortListe(): String
+ length(): int
+ {static} checkWort(wort: String): boolean
+ {static} checkUrl(url: String): boolean
}

class WortTrainer {
- wortListe : WortListe[1]
- aktuell : String[2]
- abgefragt : int
- korrekt : int
- / statistic : StringBuilder
+ WortTrainer(wortListe : WortListe)
+ ausgewaehlt() : String[]
+ randomWortEintrag() : String[]
+ check(wort : String) : boolean
+ checkIgnoreCase(wort : String) : boolean
+ getStatistic() : String
+ getAbgefragt() : int
+ setAbgefragt(abgefragt : int) : void
+ getKorrekt() : int
+ setKorrekt(korrekt : int) : void
+ getAktuell() : String[]
+ setAktuell(eintrag : String[]) : void
+ getWortListe() : WortListe
+ reset(): void
}

interface SpeichernUndLadenStrategie {
+ speichern(wortTrainer : WortTrainer) : void
+ laden() : WortTrainer
}

class SpeichernUndLaden {
- speicherpfad : String[1]
+ SpeichernUndLaden()
+ speichern(wortTrainer : WortTrainer) : void
+ laden() : WortTrainer
+ getSpeicherPfad() : String
+ setSpeicherPfad(speicherpfad : String) : void
}


class TestWorttrainerModel {
- wortListe: WortListe
- wortListe2: WortListe
- wortListe3: WortListe
+ setup() : void
+ notNullEmptyInvalid() : void
+ showTest() : void
+ addingMatchingTest() : void
+ getterTest(): void
+ setterTest() : void
+ lengthTest() : void
+ deleteTest() : void
+ getEintragTest() : void
+ alreadyInListTest() : void
+ wortCheckerTest() : void
+ urlCheckerTest() : void
}
}

package View {
class WortFrame {
+ WortFrame(layoutPanel : WortPanel)
- createMenuBar() : JMenuBar
+ {static} main(args : Strins[]) : void
}
class WortPanel {
- wortController: WortController
- bNext: JButton
- bSave: JButton
- bLoad: JButton
- textField: JTextField
- imageLabel: JLabel
- image: ImageIcon
- question: JLabel
- correct: JLabel
- amount: JLabel
- correctCounter: JLabel
- amountCounter: JLabel
+ WortPanel(wortController: WortController, correct: int, amount: int)
+ setImageUrl(String url): void
+ getTextfield(): String
+ setButtonEnabled(enabled : boolean) : void
+ refresh(correctCounter: int, amountCounter: int): void
+ reset(): void
}
}

package Controller {
class WortController {
- wortTrainer : WortTrainer
- wortView : WortFrame
- wortPanel : WortPane
- speicherStrategie : SpeichernUndLadenStrategie
+ WortController(wortTrainer : WortTrainer)
- updateImage() : void
- checkUserInput() : void
+ actionPerformed(e : ActionEvent) : void
+ insertUpdate(e : DocumentEvent) : void
+ removeUpdate(e : DocumentEvent) : void
+ changedUpdate(e : DocumentEvent) : void
+ keyReleased(e : KeyEvent) : void
+ keyTyped(e : KeyEvent) : void
+ keyPressed(e : KeyEvent) : void
+ windowOpened(e : WindowEvent) : void
+ windowClosing(e : WindowEvent) : void
+ windowClosed(e : WindowEvent) : void
+ windowIconified(e : WindowEvent) : void
+ windowDeiconified(e : WindowEvent) : void
+ windowActivated(e : WindowEvent) : void
+ windowDeactivated(e : WindowEvent) : void
+ main(args : String[]) : void
}
}
@enduml